# Uncomment this if your project is hosted on GitHub:
github_url = "https://github.com/jneug/typst-mantys/"

[version]
current = "0.0.3"

# Example of a semver regexp.
# Make sure this matches current_version before
# using tbump
regex = '''
  (?P<major>\d+)
  \.
  (?P<minor>\d+)
  \.
  (?P<patch>\d+)
  '''

[git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[file]]
src = "typst.toml"
search = 'version = "{current_version}"'

[[file]]
src = "README.md"
search = '\(v{current_version}\)'
[[file]]
src = "README.md"
search = "mantys:{current_version}"
[[file]]
src = "README.md"
search = "mantys-{current_version}"
[[file]]
src = "README.md"
search = "v{current_version}"

[[file]]
src = "docs/manual.typ"
search = 'version:\s*"{current_version}",'
[[file]]
src = "docs/manual.typ"
search = 'mantys:{current_version}'
[[file]]
src = "docs/manual.typ"
search = 'mantys/{current_version}'

[[before_commit]]
name = "create local version"
cmd = "mkdir ../mantys-{new_version}; cp -R ./* ../mantys-{new_version}"
[[before_commit]]
name = "compile manual"
cmd = "typst compile --root . docs/manual.typ"

