[page]
paper = "a4"
margin = "auto"

[fonts]
serif = ["Linux Libertine"]
sans = ["Liberation Sans", "Helvetica Neue", "Helvetica"]
mono = ["Liberation Mono"]
text = ["Linux Libertine"]
headings = ["Liberation Sans", "Helvetica Neue", "Helvetica"]
code = ["Liberation Mono"]

[font-sizes]
text = 12
headings = 12
code = 9

[colors]
primary = "red"   # [31, 158, 173]
secondary = "teal"      # [18, 120, 133]
argument =  "navy"      # [0, 29, 87]
option =    [214, 182, 93]
value =     [181, 2, 86]
command =   "blue"      # [75, 105, 197]
comment =   "gray"      # [128, 128, 128]
text =      [35, 31, 32]
muted =     210
info =      [23, 162, 184]
warning =   [255, 193, 7]
error =     [220, 53, 69]
success =   [40, 167, 69]

# Datatypes taken from typst.app
[colors.dtypes]
length = [230, 218, 255]
integer = [230, 218, 255]
float = [230, 218, 255]
fraction = [230, 218, 255]
ratio = [230, 218, 255]
"relative length" = [230, 218, 255]
none = [255, 203, 195]
auto = [255, 203, 195]
any = [255, 203, 195]
"regular expression" = [239, 240, 243]
dictionary = [239, 240, 243]
array = [239, 240, 243]
stroke = [239, 240, 243]
location = [239, 240, 243]
alignment = [239, 240, 243]
"2d alignment" = [239, 240, 243]
boolean = [255, 236, 193]
content = [166, 235, 229]
string = [209, 255, 226]
function = [249, 223, 255]
color = [
	[133, 221, 244],
	[170, 251, 198],
	[214, 247, 160],
	[255, 243, 124],
	[255, 187, 147]
]
