[package]
name = "mantys"
version = "0.1.0"
entrypoint = "src/mantys.typ"
authors = ["J. Neugebauer"]
license = "MIT"
description = "Helpers to build manuals for Typst packages."
repository = "https://github.com/jneug/typst-mantys"
